In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [10]:
data = pd.read_csv("cleaned.csv", usecols=range(2, 14))

In [5]:
data.head()

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role,Openings
0,9be62c49a0b7ebe982a4af1edaa7bc5f,2019-07-05 01:46:07 +0000,Digital Media Planner,not disclosed by recruiter,5 - 10 yrs,Media Planning| Digital Media,Advertising,Mumbai,"Marketing , Advertising , MR , PR , Media Plan...","Advertising, PR, MR, Event Management",Media Planning Executive/Manager,NaN
1,3c52d436e39f596b22519da2612f6a56,2019-07-06 08:04:50 +0000,Online Bidding Executive,not disclosed by recruiter,2 - 5 yrs,pre sales| closing| software knowledge| clien...,Retail Sales,"Pune,Pune","Sales , Retail , Business Development","IT-Software, Software Services",Sales Executive/Officer,NaN
2,ffad8a2396c60be2bf6d0e2ff47c58d4,2019-08-05 15:50:44 +0000,Trainee Research/ Research Executive- Hi- Tec...,not disclosed by recruiter,0 - 1 yrs,Computer science| Fabrication| Quality check|...,R&D,Gurgaon,"Engineering Design , R&D","Recruitment, Staffing",R&D Executive,NaN
3,7b921f51b5c2fb862b4a5f7a54c37f75,2019-08-05 15:31:56 +0000,Technical Support,"2,00,000 - 4,00,000 pa.",0 - 5 yrs,Technical Support,Admin/Maintenance/Security/Datawarehousing,Mumbai,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Support Engineer,NaN
4,2d8b7d44e138a54d5dc841163138de50,2019-07-05 02:48:29 +0000,Software Test Engineer -hyderabad,not disclosed by recruiter,2 - 5 yrs,manual testing| test engineering| test cases|...,Programming & Design,Hyderabad,IT Software - QA & Testing,"IT-Software, Software Services",Testing Engineer,NaN

In [6]:
def expfilter(x, exp):
    if type(x) == str and "yrs" in x and "-" in x:
        s = str(x).split("-")
        a = int(s[0])
        b = int(s[1][:s[1].index("y")])
        if exp in range(a, b):
            return True
        elif exp==0 and exp==a:
            return True
        return False
    if str(exp) in x:
        return True
    return False


def salfilter(x,sal):
    if type(x) == str and "-" in x and "pa." in x.lower():  # if cr crore lkh lakh la
        x = x[:x.index("pa")+2]
        s=str(x).split('-')
        p=s[0].replace(',','').strip()
        q=s[1].replace(',','').strip()
        try:
            a=int(p)
            b=int(q[:q.index("p")])
        except:
            return False
        else:
            if sal in range(a,b):
                return True
            else:
                return False
    return False

In [14]:
loc = "Mumbai"
skills = "technical support"
exp = '0'
title = "technical support"
sal = 200000
temp = data.copy()
if loc:
    temp = temp[temp['Location'].apply(lambda x:True if loc.lower() in str(x).lower() else False)]
#print(temp.head())
if skills:
    temp = temp[temp['Key Skills'].apply(lambda x:True if skills.lower() in str(x).lower() else False)]
#print(temp.loc[0, 'Uniq Id'])
if len(exp)!=0:
    temp = temp[temp['Job Experience Required'].apply(lambda x:expfilter(str(x), int(exp)))]
#print(temp.head())
if sal:
    temp = temp[temp['Job Salary'].apply(lambda x: salfilter(str(x),int(sal)))]
#print(temp.head())
if title:
    temp = temp[temp['Job Title'].apply(lambda x:True if title.lower() in str(x).lower() else False)]
#print(temp.head())

In [15]:
temp

,Uniq Id,Crawl Timestamp,Job Title,Job Salary,Job Experience Required,Key Skills,Role Category,Location,Functional Area,Industry,Role,Openings
3,7b921f51b5c2fb862b4a5f7a54c37f75,2019-08-05 15:31:56 +0000,Technical Support,"2,00,000 - 4,00,000 pa.",0 - 5 yrs,Technical Support,Admin/Maintenance/Security/Datawarehousing,Mumbai,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Support Engineer,NaN
3302,73061f356ace0ca09c85927c6f08f7ea,2019-08-04 08:46:26 +0000,"Technical Support P( Graduates in Be,bsc It,b...","2,00,000 - 4,00,000 pa.",0 - 5 yrs,Technical Support,Admin/Maintenance/Security/Datawarehousing,Mumbai,"IT Software - Application Programming , Mainte...","IT-Software, Software Services",Technical Support Engineer,NaN
8780,2eb8ba9768a56a7d82baa2ba60b0b3a1,2019-08-04 03:41:43 +0000,Technical Support Executive in a Leading BPO ...,"1,25,000 - 3,50,000 pa.",0 - 5 yrs,voice| blended| csr| international bpo| techn...,Voice,"Mumbai,Bengaluru,Pune","ITES , BPO , KPO , LPO , Customer Service , Op...","BPO, Call Centre, ITeS",Associate/Senior Associate -(Technical),NaN

In [16]:
temp.to_html()

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Uniq Id</th>\n      <th>Crawl Timestamp</th>\n      <th>Job Title</th>\n      <th>Job Salary</th>\n      <th>Job Experience Required</th>\n      <th>Key Skills</th>\n      <th>Role Category</th>\n      <th>Location</th>\n      <th>Functional Area</th>\n      <th>Industry</th>\n      <th>Role</th>\n      <th>Openings</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>3</th>\n      <td>7b921f51b5c2fb862b4a5f7a54c37f75</td>\n      <td>2019-08-05 15:31:56 +0000</td>\n      <td>Technical Support</td>\n      <td>2,00,000 - 4,00,000 pa.</td>\n      <td>0 - 5 yrs</td>\n      <td>Technical Support</td>\n      <td>Admin/Maintenance/Security/Datawarehousing</td>\n      <td>Mumbai</td>\n      <td>IT Software - Application Programming , Maintenance</td>\n      <td>IT-Software, Software Services</td>\n      <td>Technical Support Engineer</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>3302</th>\n      <td>73061f356ace0ca09c85927c6f08f7ea</td>\n      <td>2019-08-04 08:46:26 +0000</td>\n      <td>Technical Support P( Graduates in Be,bsc It,btech)</td>\n      <td>2,00,000 - 4,00,000 pa.</td>\n      <td>0 - 5 yrs</td>\n      <td>Technical Support</td>\n      <td>Admin/Maintenance/Security/Datawarehousing</td>\n      <td>Mumbai</td>\n      <td>IT Software - Application Programming , Maintenance</td>\n      <td>IT-Software, Software Services</td>\n      <td>Technical Support Engineer</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>8780</th>\n      <td>2eb8ba9768a56a7d82baa2ba60b0b3a1</td>\n      <td>2019-08-04 03:41:43 +0000</td>\n      <td>Technical Support Executive in a Leading BPO with Fixed Weekends off</td>\n      <td>1,25,000 - 3,50,000 pa.</td>\n      <td>0 - 5 yrs</td>\n      <td>voice| blended| csr| international bpo| technical| customer service| serco| call center| sales| banking| fresher| tsr| technical support| collections| uk| dayshift| airlines| non voice| bpo| process| tcs| cse| us shift| chat| looking| uk shift</td>\n      <td>Voice</td>\n      <td>Mumbai,Bengaluru,Pune</td>\n      <td>ITES , BPO , KPO , LPO , Customer Service , Operations</td>\n      <td>BPO, Call Centre, ITeS</td>\n      <td>Associate/Senior Associate -(Technical)</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>'